name: Publish auto-skip-tracks-by-duration

on:
    push:
        branches: ['main']
        paths: ['Extensions/auto-skip-tracks-by-duration/**']

jobs:
    build:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./Extensions/auto-skip-tracks-by-duration

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies
              working-directory: Extensions/auto-skip-tracks-by-duration
              run: npm ci

            - name: Build
              run: npm run build-local
              
            - name: Copy README
              run: cp README.md ./dist/README.md

            - name: Copy preview
              run: cp README.md ./dist/preview.png          
              
            - name: Publish to seperate branch
              uses: s0/git-publish-subdir-action@develop
              env:
                  REPO: self
                  BRANCH: dist/auto-skip-tracks-by-duration
                  FOLDER: ./Extensions/auto-skip-tracks-by-duration/dist
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}