name: History In Sidebar Publish

on:
    push:
        branches: ['main']
        paths: ['CustomApps/history-in-sidebar/**']

jobs:
    build:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./CustomApps/history-in-sidebar

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies
              working-directory: ./
              run: npm ci

            - name: Build
              run: npm run build-local
              
            - name: Copy Readme
              run: cp README.md ./dist/README.md

            - name: Copy preview
              run: cp preview.png ./dist/preview.png
              
            - name: Deploy
              uses: s0/git-publish-subdir-action@develop
              env:
                  REPO: self
                  BRANCH: dist/history-in-sidebar
                  FOLDER: ./CustomApps/history-in-sidebar/dist
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}