name: Publish history-in-sidebar 

on:
    push:
        branches: ['main']
        paths: ['CustomApps/playlist-tags/**']

jobs:
    build:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./CustomApps/playlist-tags

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies
              working-directory: CustomApps/playlist-tags/
              run: npm ci

            - name: Build
              run: npm run build-local
              
            - name: Copy README
              run: cp README.md ./dist/README.md

            - name: Copy preview
              run: cp README.md ./dist/preview.png          
              
            - name: Publish to seperate branch
              uses: s0/git-publish-subdir-action@develop
              env:
                  REPO: self
                  BRANCH: dist/playlist-tags
                  FOLDER: ./CustomApps/playlist-tags/dist
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
